<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6T9seRT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6T9seRT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6T9seRT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6T9seRT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6T9seRT\App_KernelDevDebugContainer([
    'container.build_hash' => '6T9seRT',
    'container.build_id' => 'dec74558',
    'container.build_time' => 1583430960,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6T9seRT');
