<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCKYROMR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCKYROMR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCKYROMR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCKYROMR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCKYROMR\App_KernelDevDebugContainer([
    'container.build_hash' => 'CKYROMR',
    'container.build_id' => '4acf4cd5',
    'container.build_time' => 1581535390,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCKYROMR');
